-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public."PasswordReset" DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public."Products" DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public."Products" DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public."RefreshTokens" DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public."Review" DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public."Review" DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS public."Stores" DROP CONSTRAINT IF EXISTS None;



DROP TABLE IF EXISTS public."Categories";

CREATE TABLE IF NOT EXISTS public."Categories"
(
    id uuid NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."PasswordReset";

CREATE TABLE IF NOT EXISTS public."PasswordReset"
(
    id uuid NOT NULL,
    "usersId" uuid NOT NULL,
    token text COLLATE pg_catalog."default" NOT NULL,
    "expiresAt" timestamp(3) with time zone NOT NULL,
    "usedAt" timestamp(3) with time zone NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."Products";

CREATE TABLE IF NOT EXISTS public."Products"
(
    id uuid NOT NULL,
    "storesId" uuid NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    prices numeric NOT NULL,
    materials character varying COLLATE pg_catalog."default" NOT NULL,
    color character varying COLLATE pg_catalog."default" NOT NULL,
    weight integer NOT NULL,
    dimension integer NOT NULL,
    status status_product NOT NULL,
    "viewCount" integer NOT NULL,
    "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    "categoriesId" uuid NOT NULL,
    guarantee character varying COLLATE pg_catalog."default" NOT NULL,
    sku character varying(15) COLLATE pg_catalog."default" NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."RefreshTokens";

CREATE TABLE IF NOT EXISTS public."RefreshTokens"
(
    id uuid NOT NULL,
    token text COLLATE pg_catalog."default" NOT NULL,
    "usersId" uuid NOT NULL,
    "expiresAt" timestamp(3) with time zone NOT NULL,
    "createdAt" timestamp(3) with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."Review";

CREATE TABLE IF NOT EXISTS public."Review"
(
    id uuid NOT NULL,
    "productsId" uuid NOT NULL,
    "usersId" uuid NOT NULL,
    rating rating_int NOT NULL,
    "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."Stores";

CREATE TABLE IF NOT EXISTS public."Stores"
(
    id uuid NOT NULL,
    "userId" uuid NOT NULL,
    "storesName" character varying COLLATE pg_catalog."default" NOT NULL,
    "storesAddress" text COLLATE pg_catalog."default" NOT NULL,
    "isVerified" boolean NOT NULL,
    "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
    "storesDescription" character varying COLLATE pg_catalog."default",
    "storesInstagram" character varying COLLATE pg_catalog."default",
    "storesNumber" character varying(15) COLLATE pg_catalog."default" NOT NULL,
    "openingHour" time without time zone,
    "closingHour" time without time zone,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."Users";

CREATE TABLE IF NOT EXISTS public."Users"
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    email character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "passwordHash" text COLLATE pg_catalog."default" NOT NULL,
    role user_role NOT NULL DEFAULT 'user'::user_role,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" time with time zone NOT NULL,
    "isActive" boolean NOT NULL DEFAULT true,
    "telephoneNumber" character varying(15) COLLATE pg_catalog."default" NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."PasswordReset"
    ADD FOREIGN KEY ("usersId")
    REFERENCES public."Users" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Products"
    ADD FOREIGN KEY ("storesId")
    REFERENCES public."Stores" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Products"
    ADD FOREIGN KEY ("categoriesId")
    REFERENCES public."Categories" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."RefreshTokens"
    ADD FOREIGN KEY ("usersId")
    REFERENCES public."Users" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Review"
    ADD FOREIGN KEY ("productsId")
    REFERENCES public."Products" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Review"
    ADD FOREIGN KEY ("usersId")
    REFERENCES public."Users" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Stores"
    ADD FOREIGN KEY ("userId")
    REFERENCES public."Users" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;